ARG BASE_IMG
FROM $BASE_IMG AS replication-builder

WORKDIR /app

RUN wget -O kapp https://github.com/vmware-tanzu/carvel-kapp/releases/download/v0.40.0/kapp-linux-amd64 && chmod +x kapp

COPY dell-csi-replicator dell-csi-replicator
RUN cd dell-csi-replicator/repctl && make build \
    && chmod +x repctl \
    && cp repctl /app

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.4-208
WORKDIR /app
COPY templates templates
COPY --from=replication-builder /app/kapp .
COPY --from=replication-builder /app/repctl ./templates
COPY "dell-common-installer" .

CMD ["/app/dell-common-installer"]

EXPOSE 8080
