// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-deployment/store (interfaces: ModuleTypeStoreInterface )

// Package mocks is a generated GoMock package.
package mocks

import (
	model "github.com/dell/csm-deployment/model"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockModuleStoreInterface is a mock of ModuleTypeStoreInterface  interface
type MockModuleStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockModuleStoreInterfaceMockRecorder
}

// MockModuleStoreInterfaceMockRecorder is the mock recorder for MockModuleStoreInterface
type MockModuleStoreInterfaceMockRecorder struct {
	mock *MockModuleStoreInterface
}

// NewMockModuleStoreInterface creates a new mock instance
func NewMockModuleStoreInterface(ctrl *gomock.Controller) *MockModuleStoreInterface {
	mock := &MockModuleStoreInterface{ctrl: ctrl}
	mock.recorder = &MockModuleStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockModuleStoreInterface) EXPECT() *MockModuleStoreInterfaceMockRecorder {
	return m.recorder
}

// GetAll mocks base method
func (m *MockModuleStoreInterface) GetAll() ([]model.ModuleType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]model.ModuleType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll
func (mr *MockModuleStoreInterfaceMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockModuleStoreInterface)(nil).GetAll))
}

// GetAllByID mocks base method
func (m *MockModuleStoreInterface) GetAllByID(arg0 ...uint) ([]model.ModuleType, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllByID", varargs...)
	ret0, _ := ret[0].([]model.ModuleType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllByID indicates an expected call of GetAllByID
func (mr *MockModuleStoreInterfaceMockRecorder) GetAllByID(arg0 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllByID", reflect.TypeOf((*MockModuleStoreInterface)(nil).GetAllByID), arg0...)
}

// GetByID mocks base method
func (m *MockModuleStoreInterface) GetByID(arg0 uint) (*model.ModuleType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0)
	ret0, _ := ret[0].(*model.ModuleType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockModuleStoreInterfaceMockRecorder) GetByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockModuleStoreInterface)(nil).GetByID), arg0)
}
