name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["type/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create a Container Storage Modules (CSM) bug report. To better help us investigate this bug, please provide the information below.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps can taken to reproduce this bug?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: "What version of CSM are you running? Specify N/A if you are not sure."
      placeholder: "v1.1.0"   
    validations:
      required: true
  - type: textarea
    id: driver
    attributes:
      label: CSI Driver(s)
      description: Please list the CSI drivers and versions that are applicable to this bug.
      placeholder: |
        1. CSI Driver for PowerFlex v2.1
        2. CSI Driver for PowerScale v2.1
    validations:
      required: false
  - type: input
    id: module
    attributes:
      label: Container Storage Module
      description: If applicable, please indicate the Container Storage Module that is relevant for this bug.
      placeholder: Authorization v1.1.0    
    validations:
      required: true
    validations:
      required: false
  - type: input
    id: co
    attributes:
      label: Container Orchestrator
      description: Which container orchestrator is being used? Please provide the version as well.
      placeholder: Kubernetes 1.2.3
    validations:
      required: true  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: "Which operating system is being used? Please provide the version as well."
      placeholder: "RHEL 7.6"
    validations:
      required: true  
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Upload logs to this bug report or provide relevant log output here.
      render: shell
    validations:
      required: false  