name: Beta - Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels: ["type/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to create a Container Storage Modules (CSM) bug report. To better help us investigate this bug, please provide the information below.
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Upload logs to this bug report or provide relevant log output here. Please be sure to remove all sensitive data such as IP addresses, host names, credentials, etc.
      render: shell
    validations:
      required: false
  - type: textarea
    id: info
    attributes:
      label: Additional Environment Information
      description: Provide additional environment information such as a listing of pods, PVs, PVCs, VolumeAttachments, Events, etc.
      render: shell
    validations:
      required: true  
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What steps can taken to reproduce this bug?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: driver
    attributes:
      label: CSI Driver(s)
      description: Please list the CSI drivers and versions that are applicable to this bug.
      placeholder: |
        CSI Driver for PowerFlex v2.1
        CSI Driver for PowerScale v2.1
        CSI Driver for PowerMax v2.1
        CSI Driver for PowerStore v2.1
        CSI Driver for Unity XT v2.1
    validations:
      required: true
  - type: textarea
    id: module
    attributes:
      label: Container Storage Modules Enabled
      description: Please list the Container Storage Modules that are enabled along with the image versions.
      placeholder: |
        Resiliency (Podmon) v1.1.0
        Replication v1.1.0
        Authorization v1.1.0 
        Observability v1.1.0
        Volume Group Snapshotter v4.2.0
    validations:
      required: true
  - type: input
    id: co
    attributes:
      label: Container Orchestrator
      description: Which container orchestrator is being used? Please provide the version as well.
      placeholder: Kubernetes 1.2.3
    validations:
      required: true  
  - type: input
    id: os
    attributes:
      label: Operating System
      description: "Which operating system is being used? Please provide the version as well."
      placeholder: "RHEL 7.6"
    validations:
      required: true