# This file maintains the latest versions for all the CSM products in the given release
# The format is as follows:
# <product> : <version>

# CSM program version
csm-version: v1.16.3

# CSM Operator version
csm-operator: v1.11.3

# Driver versions
csi-powerscale: v2.16.0
csi-powerstore: v2.16.0
csi-powermax: v2.16.2
csi-vxflexos: v2.16.1
csi-unity: v2.16.0
cosi: v1.0.0

# Module versions
csm-replication: v1.14.0
karavi-resiliency: v1.15.0
csm-authorization-v2: v2.4.0
csireverseproxy: v2.15.2
karavi-observability: v1.14.0
karavi-metrics-powerflex: v1.14.0
csm-metrics-powerstore: v1.14.0
csm-metrics-powerscale: v1.11.0
csm-metrics-powermax: v1.9.0

# Tools
cert-csi: v1.10.0
dellctl: v1.16.0
repctl: v1.14.0
installation-wizard: 1.9.0

# Third Party Libraries referred in CSM
opentelemetry-collector: 0.143.1
nginx-unprivileged: 1.29
grafana: 11.5.2
prometheus: v2.34.0
openpolicyagent-opa: 0.70.0
openpolicyagent-kube-mgmt: 9.3.0
redis: 8.4.0-alpine

# CSI Sidecar versions
csi-resizer: v2.0.0
csi-provisioner: v6.1.0
csi-node-driver-registrar: v2.15.0
csi-attacher: v4.10.0
csi-external-health-monitor-controller: v0.16.0
csi-snapshotter: v8.4.0
otel-collector : v0.150.0
