// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-deployment/prechecks (interfaces: K8sClientAPIResourceInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockK8sClientAPIResourceInterface is a mock of K8sClientAPIResourceInterface interface.
type MockK8sClientAPIResourceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockK8sClientAPIResourceInterfaceMockRecorder
}

// MockK8sClientAPIResourceInterfaceMockRecorder is the mock recorder for MockK8sClientAPIResourceInterface.
type MockK8sClientAPIResourceInterfaceMockRecorder struct {
	mock *MockK8sClientAPIResourceInterface
}

// NewMockK8sClientAPIResourceInterface creates a new mock instance.
func NewMockK8sClientAPIResourceInterface(ctrl *gomock.Controller) *MockK8sClientAPIResourceInterface {
	mock := &MockK8sClientAPIResourceInterface{ctrl: ctrl}
	mock.recorder = &MockK8sClientAPIResourceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockK8sClientAPIResourceInterface) EXPECT() *MockK8sClientAPIResourceInterfaceMockRecorder {
	return m.recorder
}

// GetAPIResource mocks base method.
func (m *MockK8sClientAPIResourceInterface) GetAPIResource(arg0 []byte, arg1 string) (*v1.APIResource, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIResource", arg0, arg1)
	ret0, _ := ret[0].(*v1.APIResource)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAPIResource indicates an expected call of GetAPIResource.
func (mr *MockK8sClientAPIResourceInterfaceMockRecorder) GetAPIResource(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIResource", reflect.TypeOf((*MockK8sClientAPIResourceInterface)(nil).GetAPIResource), arg0, arg1)
}
