// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/dell/csm-deployment/prechecks (interfaces: KubectlExplainInterface)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockKubectlExplainInterface is a mock of KubectlExplainInterface interface
type MockKubectlExplainInterface struct {
	ctrl     *gomock.Controller
	recorder *MockKubectlExplainInterfaceMockRecorder
}

// MockKubectlExplainInterfaceMockRecorder is the mock recorder for MockKubectlExplainInterface
type MockKubectlExplainInterfaceMockRecorder struct {
	mock *MockKubectlExplainInterface
}

// NewMockKubectlExplainInterface creates a new mock instance
func NewMockKubectlExplainInterface(ctrl *gomock.Controller) *MockKubectlExplainInterface {
	mock := &MockKubectlExplainInterface{ctrl: ctrl}
	mock.recorder = &MockKubectlExplainInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKubectlExplainInterface) EXPECT() *MockKubectlExplainInterfaceMockRecorder {
	return m.recorder
}

// Explain mocks base method
func (m *MockKubectlExplainInterface) Explain(arg0, arg1 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Explain", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Explain indicates an expected call of Explain
func (mr *MockKubectlExplainInterfaceMockRecorder) Explain(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*MockKubectlExplainInterface)(nil).Explain), arg0, arg1)
}
