#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("driver_secret.lib.yml", "get_arrays")

#@ def secret_name():
#@ return data.values.application + "-config"
#@ end

#! Secret for drivers
apiVersion: v1
kind: Secret
metadata:
  name: #@ secret_name()
  namespace: #@ data.values.namespace
type: Opaque
data:
  config: #@ base64.encode(get_arrays(data.values.application))
