#@ load("@ytt:data", "data")

#@ def secret_name():
#@ return data.values.application + "-certs-0"
#@ end

#! Empty Secret for unity and powerscale
apiVersion: v1
kind: Secret
metadata:
  name: #@ secret_name()
  namespace: #@ data.values.namespace
type: Opaque
data:
  cert-0: ""
