# Copyright (c) 2025 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

name: CSM Versions Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight

jobs:
  csm-versions-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Latest CSM Versions
        run: |
          bash $GITHUB_WORKSPACE/.github/scripts/update-versions.sh

      # Needed for signing commits using Github App tokens
      # See: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#commit-signing
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@v2.0.2
        id: generate-token
        with:
          app-id: ${{ vars.CSM_RELEASE_APP_ID }}
          private-key: ${{ secrets.CSM_RELEASE_APP_PRIVATE_KEY }}

      # Must enable "allow GitHub Actions to create pull requests" setting
      # Author defaults to the user who triggered the workflow run
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: "update-csi-sidecars"
          commit-message: "Update CSI sidecar versions latest"
          title: "Update CSI sidecar versions latest"
          body: |
            Automatically retrieves the latest versions of all CSI Sidecars used within CSM.
            
            Auto-generated by [csm](https://github.com/dell/csm).
          sign-commits: true
          delete-branch: true
